version: '2'
services:
  web:
    image: dockercloud/hello-world
    environment: 
      - "VIRTUAL_HOST=example.com"
    expose: 
      - "80"
networks:
  default:
    external:
      name: overlay-net
      