version: '2'
services:
  lb:
    image: dockercloud/haproxy:1.2.1
    external_links:
      - site_web_1
      - another_site_1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    network_mode: "bridge"
networks:
  default:
    external:
      name: bridge      