version: '2'
services:
  web:
    image: dockercloud/hello-world
    environment: 
      - "VIRTUAL_HOST=another.com"
    expose: 
      - "80"
    network_mode: "bridge"
networks:
  default:
    external:
      name: bridge
      